# site settings
title: Dani
subtitle: Software Developer
email: ona.dani.a@gmail.com
description: A professional geek. A software developer from the Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Dani A. Ona
street_address: Somewhere, here.
city: Davao City
state: Davao del Sur
zip_code: 8000
country: Philippines
phone: +63 921 252 8806

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/dandansoysauce
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/daniona/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/dandansoysauce

# build settings
markdown: kramdown

sass:
  style: compressed
